FROM postgres:16

RUN apt-get update && apt-get install -y \
    build-essential \
    postgresql-server-dev-16 \
    git \
    ca-certificates \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

RUN git clone --branch v0.6.0 https://github.com/pgvector/pgvector.git /tmp/pgvector

WORKDIR /tmp/pgvector
RUN make \
    && make install

WORKDIR /
RUN rm -rf /tmp/pgvector
