
FROM python:3.11-slim-bullseye

# Set the working directory
WORKDIR /app

COPY requirements.txt . 


RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        libpq-dev \
        libgomp1 \
    && pip install --no-cache-dir -r requirements.txt \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY . .

CMD ["python", "workers/worker_recomendador.py"]